Casual 1:
- Jean
- Sneakers
- Col roulé
- Bottes
- Casquette
- Bonnet
- Veste
- Pantalon
Casual 2:
- Sweatshirt
- Jean
- Sneakers
- Bonnet
- Hoodie
- Veste
- Chinos
- Pantalon
Casual hiver:
- Jean
- Trench
- T-shirt
- Cardigan
- Ceinture
- Sneakers
- Doudoune
- Bottes
- Parka
- Manteau
- Col roulé
- Bonnet
- Sac à main
- Hoodie
- Pull
- Veste
- Pantalon
Casual été:
- Sneakers, Ceinture
- Sandales
- Short
- Jean
- Ceinture
- T-shirt
- Sneakers
- Casquette
- Chemise
- Lunettes
- Sac à main
- Chinos
- Pantalon
Casual été (Femme):
- Sandales
- Short
- Ceinture
- T-shirt
- Sneakers
- Chemise
- Sac à main
Casual_hiver:
- Bottes
- Col roulé
- Manteau
- Bonnet
- Hoodie
- Pull
- Pantalon
Casual_été:
- Sandales
- Chino
- Jean
- T-shirt
- Casquette
Chic (Femme):
- Talons
- Escarpins
- Lunettes
- Sac à main
- Robe de soirée
Chic hiver (Femme):
- Talons
- Escarpins
- Manteau
- Sac à main
- Robe de soirée
Chic_femme:
- Talons
- Escarpins
- Lunettes
- Sac à main
- Robe de soirée
Chic_hiver:
- Talons
- Escarpins
- Bottes
- Manteau
- Sac à main
- Robe de soirée
Chic_été:
- Sandales
- Sac à main
- Robe de soirée
Professionnel:
- Chemise, Blazer
- Cardigan
- Chemise
- Veste
- Pantalon habillé
- T-shirt
- Col roulé
- Costume
- Chaussures de ville
- Chinos
- Pantalon
- Ceinture
- Talons
- Mocassins
- Escarpins
- Tailleur
- Manteau
- Sac à main
- Blazer
Professionnel (Femme):
- Short
- Pantalon habillé
- Ceinture
- Escarpins
- Chemise
- Chaussures de ville
- Sac à main
- Jupe
- Blazer
Professionnel (Femme) 1:
- Ceinture
- Talons
- Col roulé
- Costume
- Sac à main
Professionnel (Femme) 2:
- Ceinture
- Escarpins
- Costume
- Chemise
- Sac à main
Professionnel 1:
- Costume
- Chemise
- Chaussures de ville
- Ceinture
Professionnel 2:
- Col roulé
- Costume
- Sneakers
- Ceinture
Professionnel_femme:
- Pantalon habillé
- Escarpins
- Chemise
- Chaussures de ville
- Sac à main
- Jupe
- Blazer
Professionnel_homme:
- Pantalon habillé
- Ceinture
- Chemise
- Chaussures de ville
- Blazer
Soirée:
- Talons
- Combinaison
- Ceinture
- Sac à main
Sportswear:
- Jogging
- Sweatshirt
- T-shirt
- Sac à dos
- Sneakers
- Manteau
- Casquette
- Casquettes
- Hoodie
- Veste
- Cargo
